config/routes.rb
Rails.application.routes.draw do
  get 'users/new'

  get 'users/show'

  get 'users/edit'

  get 'users/update'

  get 'users/destroy'

  get 'users/finish_signup'

  post '/rate' => 'rater#create', :as => 'rate'
  devise_for :users, :controllers => { omniauth_callbacks: 'omniauth_callbacks',registrations: 'registrations' }
resources :books do
  member do
    put "like", to: "books#upvote"
    put "dislike", to: "books#downvote"
  end
end
  post ':id/write-book-review' , to:'books#write_review_for_book', as: :write_book_review 
  # put ':id/write-review'
  post ':id/add-to-wishlist', to: 'books#add_to_wishlist', as: :add_to_wishlist
  root 'books#index'
  match '/users/:id/finish_signup' => 'users#finish_signup', via: [:get, :patch], :as => :finish_signup
  # devise_for :users, :controllers => { registrations: 'registrations' }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord

   enum addr_typ: [:Home, :Office]
belongs_to :user 
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/average_cache.rb
class AverageCache < ActiveRecord::Base
  belongs_to :rater, :class_name => "User"
  belongs_to :rateable, :polymorphic => true
end

app/models/book.rb
class Book < ApplicationRecord
		include PublicActivity::Model
	tracked

	ratyrate_rateable 'ratings'
	acts_as_votable
	# acts_as_paranoid
	enum type:[:requested, :uploaded]
	enum availability_status:[:on, :after]


	has_one :cover, :class_name=>'Image',  as: :imageable
	has_many :reviews, as: :reviewable, dependent: :destroy

	belongs_to :user 
	accepts_nested_attributes_for :cover
	validates :name, presence: true


end

app/models/books_user.rb
class BooksUser < ApplicationRecord
end

app/models/catagory.rb
class Catagory < ApplicationRecord
	has_one :image, as: :imageable
end

app/models/city.rb
class City < ApplicationRecord
belongs_to :state
has_many :users
end

app/models/gain_point.rb
class GainPoint < ApplicationRecord
   
  enum activity: [:review_user, :review_book, :share_social, :invite_friend, :like_book, :share_book_for_free, :share_book_for_price, :return_book_to_after_date, :return_book_before_or_on_date, :not_take_book_before_auto_cancel, :add_book_to_wishlist, :rented_a_book]
   belongs_to :user

end

app/models/identity.rb
class Identity < ApplicationRecord
	belongs_to :user
	validates_presence_of :uid, :provider
	validates_uniqueness_of :uid, :scope => :provider

	def self.find_for_oauth(auth)
		find_or_create_by(uid: auth.uid, provider: auth.provider) do |identity|
			identity.name = auth.info.name
			identity.email = auth.info.email
			identity.nickname = auth.info.nickname
			identity.image = auth.info.image
			identity.phone = auth.info.phone
			identity.urls = (auth.info.urls || "").to_json
			identity.save!
			identity
		end
	end
end

app/models/image.rb
class Image < ApplicationRecord
	  belongs_to :imageable, polymorphic: true
	  mount_uploader :image, ImageUploader
end

app/models/overall_average.rb
class OverallAverage < ActiveRecord::Base
  belongs_to :rateable, :polymorphic => true
end

app/models/rate.rb
class Rate < ActiveRecord::Base
  belongs_to :rater, :class_name => "User"
  belongs_to :rateable, :polymorphic => true

  #attr_accessible :rate, :dimension

end

app/models/rating_cache.rb
class RatingCache < ActiveRecord::Base
  belongs_to :cacheable, :polymorphic => true
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :reviewable, polymorphic: true
end

app/models/shared_item.rb
class SharedItem < ApplicationRecord
end

app/models/state.rb
class State < ApplicationRecord
	has_many :cities
	has_many :users
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
 TEMP_EMAIL_PREFIX = 'change@me'
  TEMP_EMAIL_REGEX = /\Achange@me/

  # Include default devise modules. Others available are:
  # :lockable, :timeoutable
  devise :database_authenticatable, :registerable, :confirmable,
    :recoverable, :rememberable, :trackable, :validatable, :omniauthable

  validates_format_of :email, :without => TEMP_EMAIL_REGEX, on: :update

   ratyrate_rater
   has_one :image, as: :imageable
  acts_as_paranoid

  has_many :address
  has_many :books
  has_many :views ,as: :viewable
  has_one  :profile_pic ,:class_name => 'Image'  , as: :imageable
  has_many :users_reviews, :class_name => 'Review', as: :reviewable
  has_many :reviews_for_books,->{where(reviewable_type:'Book')}, :class_name => 'Review', :foreign_key => 'reviewer'
  has_many :reviews_for_users,->{where(reviewable_type:'User')}, :class_name => 'Review', :foreign_key => 'reviewer'
  belongs_to :state
  belongs_to :city 





  def self.find_for_oauth(auth, signed_in_resource = nil)

    # Get the identity and user if they exist
    identity = Identity.find_for_oauth(auth)

    # If a signed_in_resource is provided it always overrides the existing user
    # to prevent the identity being locked with accidentally created accounts.
    # Note that this may leave zombie accounts (with no associated identity) which
    # can be cleaned up at a later date.
    user = signed_in_resource ? signed_in_resource : identity.user

    # Create the user if needed
    if user.nil?

      # Get the existing user by email if the provider gives us a verified email.
      # If no verified email was provided we assign a temporary email and ask the
      # user to verify it on the next step via UsersController.finish_signup
      email_is_verified = auth.info.email && (auth.info.verified || auth.info.verified_email)
      email = auth.info.email if email_is_verified
      user = User.where(:email => email).first if email

      # Create the user if it's a new registration
      if user.nil?
        user = User.new(
          f_name: auth.extra.raw_info.first_name,
          l_name: auth.extra.raw_info.last_name,
          #username: auth.info.nickname || auth.uid,
          email: email ? email : "#{TEMP_EMAIL_PREFIX}-#{auth.uid}-#{auth.provider}.com",
          password: Devise.friendly_token[0,20]
        )
        user.skip_confirmation!
        user.save!
      end
    end

    # Associate the identity with the user if needed
    if identity.user != user
      identity.user = user
      identity.save!
    end
    user
  end

  def email_verified?
    self.email && self.email !~ TEMP_EMAIL_REGEX
  end


















         def full_name
           self.f_name + " " + self.l_name
         end

end

app/models/view.rb
class View < ApplicationRecord
	belongs_to :viewable, polymorphic: true
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  # before_action :authenticate_user!
  before_action :find_book, only:[:show,:update,:edit,:destroy, :downvote, :upvote]
  before_action :set_user 
  after_action :update_points, only:[:upvote, :downvote]


  def index
    @books =  Book.all
  end

  def show
    
  end

  def new
    @book = Book.new
    cover = @book.build_cover
  end

def create
  @book = Book.new(set_params)

  if @book.save
    redirect_to '/'
  else
    cover = @book.build_cover
    render new_book_path
  end  
end
  def edit
  end


def upvote
  @book.liked_by current_user
  redirect_to @book
end

def downvote
  @book.downvote_from current_user
  redirect_to @book
end

def update_points
  
end


def add_book_to_wishlist
  
end






private
 def find_book
 	@book = Book.find(params[:id])	
 end
 def set_user
 	@user = current_user 
 end
 def set_params
   params[:book][:user_id] = @user.id
   params.require(:book).permit(:id, :price, :published_at, :author, :user_id, :name,:cover_attributes=>[:image])
   
 end

end

app/helpers/application_helper.rb
module ApplicationHelper


end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_form.html.haml
.newBookPage
  %div.newbooktitle
    %h3 Create New Book

.row
  .col.m6.s12.stepOne
    %div.panel.panel-body.step
      = form_for @book do |f|
        - if @book.errors.any?
          .alert.alert-danger.fade.in
            %a.close{"data-dismiss" => "alert", :href => "#"} ×
            %strong Warning!
            #error_explanation
              %h2
                = pluralize(@book.errors.count, "error")
                prohibited this book from being saved:
              %ul
                - @book.errors.full_messages.each do |message|
                  %li= message
        .form-group
          = f.label :name
          = f.text_field :name , class:"form-control", placeholder:"Book Name"
        .form-group
          = f.label :author
          = f.text_field :author , class:"form-control", placeholder:"Book's Author Name"
        .form-group
          = f.label :availability
          .input-group.date{"data-provide" => "datepicker"}
            = f.text_field :availability , class:"form-control ", placeholder:"Book will be availabale"
            .input-group-addon
              %span.glyphicon.glyphicon-th
          .form-group
            = f.label :availability_status
            = f.select  :availability_status, Book.availability_statuses.keys
        .form-group
          = f.label :published_at
          .input-group.date{"data-provide" => "datepicker"}
            = f.text_field :published_at , class:"form-control ", placeholder:"Book's Publishing Date"
            .input-group-addon
              %span.glyphicon.glyphicon-th
        .form-group
          = f.label :price
          %span{style: "float: right;"}
            %span{style: "font-size:.8em; margin-left:40px"} 
              Leave it if share for 
            %span{style: "color: #fff; background-color: #87c540; padding:2px 2px; border-radius:2px;"}FREE
          = f.text_field :price , class:"form-control", value: 0.0
        .form-group
          = f.fields_for :cover do |ff|
            = ff.label :image, "Upload Book's Cover"
            = ff.file_field :image 
        .form-group  
          .actions
            = f.submit "Create Book" ,class:"btn btn-default",style:"color:#fff ; background-color:#87c540 ;box-shadow: 3px 3px 8px #888888;"
  .col.m6.s12.stepTwo
    %div.panel.panel-body.step
      = form_for @book do |f|
        - if @book.errors.any?
          .alert.alert-danger.fade.in
            %a.close{"data-dismiss" => "alert", :href => "#"} ×
            %strong Warning!
            #error_explanation
              %h2
                = pluralize(@book.errors.count, "error")
                prohibited this book from being saved:
              %ul
                - @book.errors.full_messages.each do |message|
                  %li= message
        .form-group
          = f.label :name
          = f.text_field :name , class:"form-control", placeholder:"Book Name"
        .form-group
          = f.label :author
          = f.text_field :author , class:"form-control", placeholder:"Book's Author Name"
        .form-group
          = f.label :availability
          .input-group.date{"data-provide" => "datepicker"}
            = f.text_field :availability , class:"form-control ", placeholder:"Book will be availabale"
            .input-group-addon
              %span.glyphicon.glyphicon-th
          .form-group
            = f.label :availability_status
            = f.select  :availability_status, Book.availability_statuses.keys
        .form-group
          = f.label :published_at
          .input-group.date{"data-provide" => "datepicker"}
            = f.text_field :published_at , class:"form-control ", placeholder:"Book's Publishing Date"
            .input-group-addon
              %span.glyphicon.glyphicon-th
        .form-group
          = f.label :price
          %span{style: "float: right;"}
            %span{style: "font-size:.8em; margin-left:40px"} 
              Leave it if share for 
            %span{style: "color: #fff; background-color: #87c540; padding:2px 2px; border-radius:2px;"}FREE
          = f.text_field :price , class:"form-control", value: 0.0
        .form-group
          = f.fields_for :cover do |ff|
            = ff.label :image, "Upload Book's Cover"
            = ff.file_field :image 
        .form-group  
          .actions
            = f.submit "Create Book" ,class:"btn btn-default",style:"color:#fff ; background-color:#87c540 ;box-shadow: 3px 3px 8px #888888;"

app/views/books/edit.html.erb
<%render 'form'%>

app/views/books/index.html.erb
	 <main>
	 	<div class="section img-responsive" id="section1">
	 		Share My Book Animation
	 	</div>
	 	<div class="section img-responsive" id="section2">
	 		<%= link_to 'create book' , new_book_path , class:"btn btn-info btn-xs"%>
	 		<div class="row">
	 			<%if @books.present?%>
	 			<%@books.each do |book| %>
	 			<div class="col-md-3 col-xs-12">
	 				<div class="card", style="max-width:446px;">
	 					<%= image_tag(book.cover.image.url,class:"card-img-top img-fluid img-responsive") if book.cover.present? %>
	 					<div class="card-block">
	 						<h4 class="card-title"><%= book.name %></h4>
	 						<p class="card-text">This is a longer card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>
	 						<h5>Author</h5><%= book.author%> <br>
	 						<h5>Uploaded at </h5>

	 						<%= book.published_at%><br>
	 					</div>
	 				</div>
	 				<%= rating_for book, "ratings", disable_after_rate: true, enable_half: true, half_show: true %>
	 				<%= link_to 'show', book_path(book)%>
	 			</div>
	 			<%end%>
	 			<%end%>	 
	 		</div>
	 	</div>   
	 	<div class="section img-responsive" id="section3">
	 		Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
	 		tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
	 		quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
	 		consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
	 		cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
	 		proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
	 	</div>   
	 	<div class="section img-responsive" id="section4">
	 		Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
	 		tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
	 		quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
	 		consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
	 		cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
	 		proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
	 	</div>
	 </main>





	 <script>
	 	$(document).ready(function(){
	 		var section1_OffsetTop = $('#section1').offset().top-60;
	 		var section2_OffsetTop = $('#section2').offset().top-60;
	 		var section3_OffsetTop = $('#section3').offset().top-60;
	 		var section4_OffsetTop = $('#section4').offset().top-60;

	 		function changeTab(hash){
	 			hash = hash.substring(1);
	 			$('ol.carousel-indicators>li a[href$='+hash+']').parent().siblings().removeClass('active');
	 			$('ol.carousel-indicators>li a[href$='+hash+']').parent().addClass('active');
	 		}

	 		$(window).scroll(function(event) {
	 			/* Act on the event */
	 			var $currentTab = '';
	 			var wPosition  = $(window).scrollTop();
	 			if (wPosition > section1_OffsetTop && wPosition <section2_OffsetTop){
	 				$currentTab = $('ol.carousel-indicators>li>a').eq(0)[0];
	 				console.log('section1');
	 			}
	 			else if (wPosition >= section2_OffsetTop && wPosition < section3_OffsetTop) {
	 				$currentTab = $('ol.carousel-indicators>li>a').eq(1)[0];
	 				console.log('section2');
	 			}else if (wPosition >= section3_OffsetTop&& wPosition < section4_OffsetTop) {
	 				$currentTab = $('ol.carousel-indicators>li>a').eq(2)[0];
	 				console.log('section3');
	 			}else if (wPosition >= section4_OffsetTop) {
	 				$currentTab = $('ol.carousel-indicators>li>a').eq(3)[0];
	 				console.log('sectio4');
	 			}
	 			else{
	 				console.log('Nothing');
	 				console.log(wPosition);
	 				console.log(section1_OffsetTop);
	 				console.log(section2_OffsetTop);
	 				console.log(section3_OffsetTop);
	 				console.log(section4_OffsetTop);
	 			}
	 			var	activeTabCaro = 'ol.carousel-indicators>li a[href$='+$currentTab.hash.substring(1)+']';
	 			var isActiveTabCaro = $(activeTabCaro).parent().hasClass('active');
	 			console.log(isActiveTabCaro);
	 			if(isActiveTabCaro) {
	 			}
	 			else{
	 				changeTab($currentTab.hash);
	 			}
	 		});
	 		$('ol.carousel-indicators>li>a').click(scrolling);
	 	});
	 </script>
	 <style type="text/css" media="screen">
	 	.container{
	 		perspective: 1000px;
	 		margin-top:50px;
	 	}
	 	.container-fluid >.carousel-indicators{
	 		display: flex;
	 	}
	 </style>

app/views/books/new.html.haml
=render 'form'
 

app/views/books/show.html.haml
.container-fluild
  .row
    .col-md-6.col-xs-12 
      %div{class:"image_div"}
        Rate this Book  : 
        =rating_for @book, 'ratings',disable_after_rate: false, enable_half: true, half_show: true
        =image_tag(@book.cover.image.url) 
        %br
        =@book.name
        %br
        =@book.author
        %br
        =@book.published_at
        %br
        =@book.price
        %br
        =@book.description
        = @book.get_likes.size
        = link_to like_book_path(@book), method: :put do 
          %span{class:"glyphicon glyphicon-thumbs-up"}
        = @book.get_dislikes.size
        = link_to dislike_book_path(@book), method: :put do
          %span{class:"glyphicon glyphicon-thumbs-down"} 